version: "0.5"

processes:
  service:
    command: "RUST_BACKTRACE=1 cargo run"
    availability:
      restart: "always"
    depends_on:
      reset_database:
        condition: process_completed

  reset_database:
    command: "sqlx database reset -y"

  service_available:
    command: "./scripts/check_availability.sh"

  simulation:
    command: "cd simulation && julia --project simulation.jl"
    availability:
      restart: "never"
    depends_on:
      service_available:
        condition: process_completed

