---
title: "Untitled"
output: html_document
date: "2024-12-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(DBI)
library(dplyr)
library(tidyr)
library(ggplot2)

DB_PATH <- Sys.getenv("DATABASE_PATH")
db <- dbConnect(RSQLite::SQLite(), DB_PATH)

```


## Datasets

```{r}
qn_samples <- tbl(db, "rank_history") %>% 
  inner_join(
    tbl(db, "stats_history"),
    by = c("item_id", "interval_id")
  ) %>% 
  select(item_id, interval_id, rank_top, rank_new, upvote_share) %>% 
  mutate(
    rank_top = as.numeric(rank_top),
    rank_new = as.numeric(rank_new),
  ) %>% 
  data.frame()
  
vote_events <- tbl(db, "vote_event") %>% data.frame()
```


## Sanity Checks

```{r}
qn_samples %>% 
  arrange(item_id, interval_id) %>% 
  filter(item_id == 7) %>%
  select(interval_id, rank_top, rank_new, upvote_share) %>% 
  pivot_longer(c("rank_top", "rank_new")) %>% 
  mutate(name = as.factor(name)) %>% 
  ggplot(aes(x = as.numeric(interval_id), y = value, color = name)) +
  geom_point(aes(size = upvote_share)) +
  geom_line() +
  scale_x_continuous(breaks = seq(0, 1000, 10)) + 
  scale_y_continuous(trans = "reverse", breaks = seq(0, 1000, 10))

vote_events %>% 
  group_by(page) %>% 
  summarize(count = n()) %>% 
  ungroup() %>% 
  ggplot(aes(x = page, y = count)) +
  geom_histogram(stat = "identity")

vote_events %>% 
  group_by(rank, page) %>% 
  summarize(count = n()) %>% 
  ungroup() %>% 
  mutate(
    rank = as.numeric(rank),
    count = as.numeric(count)
  ) %>% 
  ggplot(aes(x = rank, y = count, color = page)) +
  geom_line() +
  geom_point()

```


## Oversimlified Model

```{r, eval=FALSE}
model <- lm(upvote_share ~ rank_top + rank_new, data = qn_samples)
summary(model)

data_sample <- data.frame(
  rank_top = c(1, 5, 32),
  rank_new = c(17, 61, 74)
)

predict.lm(model, data_sample)

```



```{r}
dbDisconnect(db)

```